apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-timescale
  namespace: security-lab

data:
  vault-agent.hcl: |
    vault {
      address = "http://vault:8200"
    }

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "timescaledb"
        }
      }

      sink "file" {
        config = {
          path = "/vault/secrets/token"
        }
      }
    }

    template {
      source = "/etc/vault/template/db.ctmpl"
      destination = "/vault/secrets/db.env"
    }