apiVersion: v1
kind: Pod
metadata:
  name: admin-test-agent
  namespace: security-lab
spec:
  serviceAccountName: admin

  volumes:
    - name: vault-secrets
      emptyDir: {}

    - name: vault-config
      configMap:
        name: vault-agent-config

    - name: vault-template
      configMap:
        name: vault-agent-template

  containers:

    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets

    - name: vault-agent
      image: hashicorp/vault:1.19
      command: ["vault", "agent", "-config=/etc/vault/vault-agent.hcl"]
      volumeMounts:
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-template
          mountPath: /etc/vault/template
        - name: vault-secrets
          mountPath: /vault/secrets