apiVersion: v1
kind: Pod

metadata:
  name: audit-test
  namespace: security-lab

spec:

  serviceAccountName: audit

  containers:

  - name: alpine

    image: alpine:3.20

    command:
      - sleep

    args:
      - "3600"