apiVersion: v1
kind: ConfigMap

metadata:
  name: vault-config
  namespace: security-lab

data:

  vault.hcl: |

    ui = true

    api_addr = "http://vault:8200"

    storage "file" {
      path = "/vault/data"
    }

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }